# Generated by Django 3.2.18 on 2023-05-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='titel',
            new_name='title',
        ),
    ]
