---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Logun to Docker Hub
        user: docker/login-action@v1
        with:
          username: ${{ secret.DOCKERHUB_USER }}
          password: ${{ secret.DOCKERHUB_TOKEN }}
      - name: Checkout
        user: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"